<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ProjectLakeShoreDrive.Shared\ProjectLakeShoreDrive.Shared.csproj" />
    <ProjectReference Include="..\ProjectLakeShoreDrive.Messaging.Abstractions\ProjectLakeShoreDrive.Messaging.Abstractions.csproj" />
  </ItemGroup>

</Project>
