<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ProjectLakeShoreDrive.Knowledge.Core\ProjectLakeShoreDrive.Knowledge.Core.csproj" />
    <ProjectReference Include="..\..\ProjectLakeShoreDrive.ServiceDefaults\ProjectLakeShoreDrive.ServiceDefaults.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
