// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectLakeShoreDrive.Engagement.Core.Persistence;

#nullable disable

namespace ProjectLakeShoreDrive.Engagement.Persistence.Migrations
{
    [DbContext(typeof(EngagementDbContext))]
    partial class EngagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectLakeShoreDrive.Engagement.Core.Domain.Engagement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.PrimitiveCollection<string>("BusinessObjectives")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessProblem")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Confidentiality")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Constraints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrentStateSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.PrimitiveCollection<string>("KnownTechnologyLandscape")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.PrimitiveCollection<string>("RequestedDeliverables")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetStateSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_Engagements_Status_CreatedAtUtc");

                    b.ToTable("Engagements", (string)null);
                });

            modelBuilder.Entity("ProjectLakeShoreDrive.Engagement.Core.Domain.Engagement", b =>
                {
                    b.OwnsOne("ProjectLakeShoreDrive.Engagement.Core.Domain.ClientReference", "Client", b1 =>
                        {
                            b1.Property<Guid>("EngagementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ClientId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ClientName");

                            b1.HasKey("EngagementId");

                            b1.HasIndex("ClientId")
                                .HasDatabaseName("IX_Engagements_ClientId");

                            b1.ToTable("Engagements");

                            b1.WithOwner()
                                .HasForeignKey("EngagementId");
                        });

                    b.OwnsMany("ProjectLakeShoreDrive.Engagement.Core.Domain.EngagementLifecycleTransition", "LifecycleHistory", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("EngagementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("FromStatus")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset>("OccurredAtUtc")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("PerformedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Reason")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<int>("ToStatus")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("EngagementId", "OccurredAtUtc")
                                .HasDatabaseName("IX_EngagementLifecycleTransitions_EngagementId_OccurredAtUtc");

                            b1.ToTable("EngagementLifecycleTransitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EngagementId");
                        });

                    b.OwnsOne("ProjectLakeShoreDrive.Engagement.Core.Domain.EngagementTimeline", "Timeline", b1 =>
                        {
                            b1.Property<Guid>("EngagementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("TimelineStartDate");

                            b1.Property<DateOnly?>("TargetEndDate")
                                .HasColumnType("date")
                                .HasColumnName("TimelineTargetEndDate");

                            b1.HasKey("EngagementId");

                            b1.ToTable("Engagements");

                            b1.WithOwner()
                                .HasForeignKey("EngagementId");
                        });

                    b.OwnsMany("ProjectLakeShoreDrive.Engagement.Core.Domain.Stakeholder", "Stakeholders", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Email")
                                .HasMaxLength(320)
                                .HasColumnType("nvarchar(320)");

                            b1.Property<Guid>("EngagementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("Id");

                            b1.HasIndex("EngagementId");

                            b1.ToTable("EngagementStakeholders", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EngagementId");
                        });

                    b.Navigation("Client")
                        .IsRequired();

                    b.Navigation("LifecycleHistory");

                    b.Navigation("Stakeholders");

                    b.Navigation("Timeline");
                });
#pragma warning restore 612, 618
        }
    }
}
